export enum ActionTypes {
  API_DISHES_REQUEST = 'API_DISHES_REQUEST',
  API_DISHES_SUCCESS = 'API_DISHES_SUCCESS',
  API_DISHES_FAILURE = 'API_DISHES_FAILURE',

  API_ADD_NEW_DISH_SUCCESS = 'API_ADD_NEW_DISH_SUCCESS',

  SET_CURRENT_SEARCH = 'SET_CURRENT_SEARCH',
}
